spring:
  datasource:
    username: { USER_NAME }
    password: { PASSWORD }
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
db:
  url:
    writer: jdbc:mysql://{ HOST }:{ PORT }/{ DB }?useSSL=false&useUnicode=true&serverTimezone=UTC&autoReconnect=true
    reader: jdbc:mysql://{ HOST }:{ PORT }/{ DB }?useSSL=false&useUnicode=true&serverTimezone=UTC&autoReconnect=true
logging:
  level:
    root: info
    org.springframework.*: info
    org.hibernate: info
    io.swagger.*: error
